version: '3.8'
services:
  bot-cybernyan:
    build: .
    env_file: 
      - .env
    volumes:
      - .:/usr/src/app
    command: /bin/bash -c "python bot/cybernyan.py"
  bot-cyberwan:
    build: .
    env_file: 
      - .env
    volumes:
      - .:/usr/src/app
    command: /bin/bash -c "python bot/cyberwan.py"
    
  # bot-cyberchun:
  #   build: .
  #   env_file: 
  #     - .env
  #   volumes:
  #     - .:/usr/src/app
  #   command: /bin/bash -c "python bot/cyberchun.py"